In [2]:
import sqlite3
import pandas as pd
import time
from nba_api.stats.static import players
from nba_api.stats.endpoints import commonplayerinfo
from nba_api.stats.endpoints import shotchartdetail

### Function to Fetch all Active Centers

In [3]:
conn = sqlite3.connect('nba_centers_info.db')

def get_center_data(start, end):
    # Get names of all active players
    active_centers = players.get_active_players()

    # Ran function in sections to help with avoiding getting flagged 
    section = active_centers[start:end]
    
    center_details = []
    
    # Loop through players to get desired information
    for player in section:
        player_id = player['id']
        print(f"Fetching details for {player['full_name']}...")
        
        try:
            # Fetch desired info
            info = commonplayerinfo.CommonPlayerInfo(player_id=player_id)
            df = info.get_data_frames()[0]
            
            # Select only the desired columns
            desired_info = df[['PERSON_ID', 'DISPLAY_FIRST_LAST', 'POSITION', 'HEIGHT', 'TEAM_NAME']]
            center_details.append(desired_info)
            
            time.sleep(1) 
            
        except Exception as e:
            print(f"Error fetching {player['full_name']}: {e}")
            
    # Specified to only add players who play Center into data frame   
    # Used if_exists='append' to add new centers to data frame 
    if center_details:
        final_df = pd.concat(center_details, ignore_index=True)

        final_df = final_df[final_df['POSITION'] == 'Center']
        
        final_df.to_sql('Centers', conn, if_exists='append', index=False)
        print(final_df)

In [4]:
active_centers = players.get_active_players()
len(active_centers)

530

In [ ]:
get_center_data(0, 100)

In [ ]:
get_center_data(101, 200)

In [ ]:
get_center_data(201, 300)

In [ ]:
get_center_data(301, 400)

In [ ]:
get_center_data(401, 500)

In [ ]:
get_center_data(501, 530)

### Function to Fetch all Inactive Centers

In [5]:
conn = sqlite3.connect('nba_centers_info.db')

def get_center_data(start, end):
    # Get names of all inactive players
    inactive_centers = players.get_inactive_players()

    # Ran function in sections to help with avoiding getting flagged 
    section = inactive_centers[start:end]
    
    inactive_center_details = []
    
    # Loop through players to get desired information
    for player in section:
        player_id = player['id']
        print(f"Fetching details for {player['full_name']}...")
        
        try:
            # Fetch desired info
            info = commonplayerinfo.CommonPlayerInfo(player_id=player_id)
            df = info.get_data_frames()[0]
            
            # Select only the desired columns
            desired_info = df[['PERSON_ID', 'DISPLAY_FIRST_LAST', 'POSITION', 'HEIGHT', 'TEAM_NAME']]
            inactive_center_details.append(desired_info)
            
            time.sleep(2) 
            
        except Exception as e:
            print(f"Error fetching {player['full_name']}: {e}")

    # Specified to only add players who play Center into data frame   
    # Used if_exists='append' to add new centers to data frame 
    if inactive_center_details:
        final_df = pd.concat(inactive_center_details, ignore_index=True)

        final_df = final_df[final_df['POSITION'] == 'Center']

        final_df.to_sql('Centers', conn, if_exists='append', index=False)
        print(final_df)

In [6]:
inactive_centers = players.get_inactive_players()
len(inactive_centers)

4573

In [ ]:
get_center_data(0, 100)

In [ ]:
get_center_data(101, 200)

In [ ]:
get_center_data(201, 300)

In [ ]:
get_center_data(301, 400)

In [ ]:
get_center_data(401, 500)

In [ ]:
get_center_data(501, 600)

In [ ]:
get_center_data(601, 700)

In [ ]:
get_center_data(701, 800)

In [ ]:
get_center_data(801, 900)

In [ ]:
get_center_data(901, 1000)

In [ ]:
get_center_data(1001, 1100)

In [ ]:
get_center_data(1101, 1200)

In [ ]:
get_center_data(1201, 1300)

In [ ]:
get_center_data(1301, 1400)

In [ ]:
get_center_data(1401, 1500)

In [ ]:
get_center_data(1501, 1600)

In [ ]:
get_center_data(1601, 1700)

In [ ]:
get_center_data(1701, 1800)

In [ ]:
get_center_data(1801, 1900)

In [ ]:
get_center_data(1901, 2000)

In [ ]:
get_center_data(2001, 2100)

In [ ]:
get_center_data(2101, 2200)

In [ ]:
get_center_data(2201, 2300)

In [ ]:
get_center_data(2301, 2400)

In [ ]:
get_center_data(2401, 2500)

In [ ]:
get_center_data(2501, 2600)

In [ ]:
get_center_data(2601, 2700)

In [ ]:
get_center_data(2701, 2800)

In [ ]:
get_center_data(2801, 2900)

In [ ]:
get_center_data(2901, 3000)

In [ ]:
get_center_data(3001, 3100)

In [ ]:
get_center_data(3101, 3200)

In [ ]:
get_center_data(3201, 3300)

In [ ]:
get_center_data(3301, 3400)

In [ ]:
get_center_data(3401, 3500)

In [ ]:
get_center_data(3501, 3600)

In [ ]:
get_center_data(3601, 3700)

In [ ]:
get_center_data(3701, 3800)

In [ ]:
get_center_data(3801, 3900)

In [ ]:
get_center_data(3901, 4000)

In [ ]:
get_center_data(4001, 4100)

In [ ]:
get_center_data(4101, 4200)

In [ ]:
get_center_data(4201, 4300)

In [ ]:
get_center_data(4301, 4400)

In [ ]:
get_center_data(4401, 4500)

In [ ]:
get_center_data(4501, 4573)

In [6]:
conn = sqlite3.connect('nba_centers_info.db')

centers_df = pd.read_sql("SELECT * FROM Centers", conn)
centers_df

     PERSON_ID DISPLAY_FIRST_LAST POSITION HEIGHT  TEAM_NAME
0       203500       Steven Adams   Center   6-11    Rockets
1      1628386      Jarrett Allen   Center    6-9  Cavaliers
2      1629028      Deandre Ayton   Center    7-0     Lakers
3       202687    Bismack Biyombo   Center    6-8      Spurs
4       203991       Clint Capela   Center   6-10    Rockets
..         ...                ...      ...    ...        ...
696       1917       Wang Zhi-zhi   Center    7-1
697        678       George Zidek   Center    7-0
698    1627757  Stephen Zimmerman   Center    7-0      Magic
699    1627790         Ante Zizic   Center   6-10  Cavaliers
700      78647           Jim Zoet   Center    7-1    Pistons

[701 rows x 5 columns]

In [ ]:
conn.close()

### Function to Fetch Shot Loctions

In [17]:
conn = sqlite3.connect('nba_centers_info.db')

def get_shot_loc(start,end):
    desired_seasons = [f"{year}-{str(year+1)[2:]}" for year in range(start, end + 1)]

    seasons = desired_seasons

    shot_loc = []

    for season in seasons: 
        print(f"Fetching player shot locations for {season}...")

        try:
            info = shotchartdetail.ShotChartDetail(
                team_id = 0,
                player_id = 0,
                season_nullable = season, 
                context_measure_simple = 'FGA', 
                season_type_all_star = 'Regular Season')
            df = info.get_data_frames()[0]

            desired_info = df[['PLAYER_ID', 'PLAYER_NAME', 'TEAM_NAME', 'PERIOD', 
                               'EVENT_TYPE', 'SHOT_TYPE', 'SHOT_DISTANCE', 'LOC_X', 'LOC_Y']]

            shot_loc.append(desired_info)

            time.sleep(1)

        except Exception as e:
            print(f"Error {e}")

    if shot_loc:
        final_df = pd.concat(shot_loc, ignore_index=True)
        
        # Add to the 'ShotLocations' table
        final_df.to_sql('ShotLocs', conn, if_exists='append', index=False)
        print(final_df)

In [ ]:
get_shot_loc(2013, 2024)

In [12]:
conn = sqlite3.connect('nba_centers_info.db')

shot_loc_df = pd.read_sql("SELECT * FROM ShotLocs", conn)
shot_loc_df

,PLAYER_ID,PLAYER_NAME,TEAM_NAME,PERIOD,EVENT_TYPE,SHOT_TYPE,SHOT_DISTANCE,LOC_X,LOC_Y
0,2561,David West,Indiana Pacers,1,Missed Shot,2PT Field Goal,5.0,-38.0,45.0
1,202331,Paul George,Indiana Pacers,1,Made Shot,2PT Field Goal,19.0,105.0,164.0
2,201167,Arron Afflalo,Orlando Magic,1,Missed Shot,3PT Field Goal,27.0,51.0,266.0
3,2561,David West,Indiana Pacers,1,Missed Shot,2PT Field Goal,2.0,28.0,-5.0
4,202362,Lance Stephenson,Indiana Pacers,1,Made Shot,3PT Field Goal,26.0,15.0,260.0
...,...,...,...,...,...,...,...,...,...
2510333,1630578,Alperen Sengun,Houston Rockets,4,Missed Shot,3PT Field Goal,25.0,-29.0,257.0
2510334,1627832,Fred VanVleet,Houston Rockets,4,Missed Shot,3PT Field Goal,22.0,-228.0,-17.0
2510335,1629652,Luguentz Dort,Oklahoma City Thunder,4,Made Shot,3PT Field Goal,24.0,186.0,167.0
2510336,1630224,Jalen Green,Houston Rockets,4,Made Shot,2PT Field Goal,2.0,12.0,16.0
2510337,1630224,Jalen Green,Houston Rockets,4,Missed Shot,3PT Field Goal,25.0,-218.0,132.0

In [13]:
conn = sqlite3.connect('nba_centers_info.db')

centers_df = pd.read_sql("SELECT * FROM Centers", conn)
centers_df

     PERSON_ID DISPLAY_FIRST_LAST POSITION HEIGHT  TEAM_NAME
0       203500       Steven Adams   Center   6-11    Rockets
1      1628386      Jarrett Allen   Center    6-9  Cavaliers
2      1629028      Deandre Ayton   Center    7-0     Lakers
3       202687    Bismack Biyombo   Center    6-8      Spurs
4       203991       Clint Capela   Center   6-10    Rockets
..         ...                ...      ...    ...        ...
696       1917       Wang Zhi-zhi   Center    7-1
697        678       George Zidek   Center    7-0
698    1627757  Stephen Zimmerman   Center    7-0      Magic
699    1627790         Ante Zizic   Center   6-10  Cavaliers
700      78647           Jim Zoet   Center    7-1    Pistons

[701 rows x 5 columns]

In [28]:
pd.read_sql('''SELECT 
            sl.PLAYER_NAME,
            c.POSITION,
            sl.TEAM_NAME,
            sl.LOC_X,
            sl.LOC_Y
            FROM ShotLocs as sl
            INNER JOIN Centers as c
            ON sl.PLAYER_ID = c.PERSON_ID''', conn)

           PLAYER_NAME POSITION        TEAM_NAME  LOC_X  LOC_Y
0          Roy Hibbert   Center   Indiana Pacers   13.0    9.0
1          Roy Hibbert   Center   Indiana Pacers    4.0    0.0
2          Roy Hibbert   Center   Indiana Pacers  -97.0   15.0
3       Nikola Vučević   Center    Orlando Magic  -48.0    7.0
4       Nikola Vučević   Center    Orlando Magic   12.0    0.0
...                ...      ...              ...    ...    ...
201033  Alperen Sengun   Center  Houston Rockets  -17.0   41.0
201034  Alperen Sengun   Center  Houston Rockets  146.0  220.0
201035  Alperen Sengun   Center  Houston Rockets   64.0  101.0
201036  Alperen Sengun   Center  Houston Rockets   10.0    0.0
201037  Alperen Sengun   Center  Houston Rockets  -29.0  257.0

[201038 rows x 5 columns]

In [32]:
pd.read_sql('''SELECT 
            sl.PLAYER_NAME,
            c.POSITION,
            sl.TEAM_NAME,
            sl.LOC_X,
            sl.LOC_Y
            FROM ShotLocs as sl
            INNER JOIN Centers as c
            ON sl.PLAYER_ID = c.PERSON_ID
            WHERE sl.PLAYER_NAME = 'Steven Adams' ''', conn)

       PLAYER_NAME POSITION              TEAM_NAME  LOC_X  LOC_Y
0     Steven Adams   Center  Oklahoma City Thunder   18.0   12.0
1     Steven Adams   Center  Oklahoma City Thunder   -4.0    6.0
2     Steven Adams   Center  Oklahoma City Thunder    2.0    9.0
3     Steven Adams   Center  Oklahoma City Thunder   15.0    3.0
4     Steven Adams   Center  Oklahoma City Thunder  -16.0   33.0
...            ...      ...                    ...    ...    ...
4781  Steven Adams   Center        Houston Rockets  -17.0   15.0
4782  Steven Adams   Center        Houston Rockets    0.0    0.0
4783  Steven Adams   Center        Houston Rockets   20.0   50.0
4784  Steven Adams   Center        Houston Rockets    0.0    0.0
4785  Steven Adams   Center        Houston Rockets    0.0    0.0

[4786 rows x 5 columns]

In [ ]:
conn.close()